insert into studio(japanese_name, name, description, comment)
values
	('瑞鷹株式会社', '', '', ''),
	('日本アニメーション', 'Nippon Animation Co., Ltd.', '前身為瑞鷹', '日本動畫公司'),
	('株式会社マッドハウス', 'MADHOUSE Inc.', '', ''),
	('株式会社ジーベック', 'XEBEC', '', ''),
	('株式会社スタジオディーン', 'STUDIO DEEN Co.,Ltd.', '', 'STUDIO DEEN Co.,Ltd.'),
	('株式会社ぴえろ', 'Pierrot Co.,Ltd.', '', 'Studio Pierrot'),
	('株式会社グループ・タック', 'Group Tac Co.,Ltd.', '', 'Group Tac'),
	('東映アニメーション株式会社', 'TOEI ANIMATION CO., LTD.', '', '東映動畫'),
	('株式会社サンライズ', 'SUNRISE INC.', '', '日昇動畫'),
	('株式会社ジェー·シー·スタッフ', 'J.C.STAFF Co.,Ltd.', '', 'J.C.STAFF'),
	('株式会社ミルキーカートゥーン', 'Milky Cartoon', '', 'Milky Cartoon Co., Ltd'),
	('株式会社トムス・エンタテインメント', 'TMS Entertainment', '東京Movie、東京電影', 'TMS ENTERTAINMENT'),
	('株式会社ゴンゾ', 'GONZO K.K.', '', ''),
	('株式会社スタジオフラッグ', 'studio FLAG', '', 'スタジオフラッグ'),
	('Public&Basic', '', '', ''),
	('PLUM', '', '', ''),
	('株式会社タツノコプロダクション', 'Tatsunoko Production Co. Ltd.', '', '龍之子製作公司'),
	('株式会社ぎゃろっぷ', 'GALLOP', '', 'GALLOP Co.,Ltd.'),
	('スタジオジブリ', 'Studio Ghibli Inc.', '', '吉卜力工作室'),
	('株式会社 イージー・フイルム', 'E&G FILMS', '', ''),
	('ハルフィルムメーカー', 'Hal Film Maker', '', ''),
	('Tomason', '', '', ''),
	('スタジオ雲雀', '', '', '雲雀工作室'),
	('有限会社トライアングルスタッフ', 'Triangle Staff', '', 'Triangle Staff Co., Ltd.'),
	('株式会社トランス・アーツ', 'TRANS ARTS', '', ''),
	('株式会社プロダクション・アイジー', 'Production I.G', '', ''),
	('株式会社ティー·エヌ·ケー', 'TNK', '', 'TNK Co.,Ltd'),
	('株式会社ポリゴン・ピクチュアズ', 'Polygon Pictures', '', ''),
	('有限会社アナザープッシュピンプランニング', 'A.P.P.P', '', 'A.P.P.P. Co., Ltd.'),
	('', '', 'none', ''),
	('株式会社ラディクスエースエンタテインメント', 'RADIX', '', 'RADIX ACE ENTERTAINMENT Co.,Ltd.'),
	('NOA', 'NOA', '', ''),
	('スタジオ OX', 'Studio OX', '', ''),
	('株式会社ボンズ', 'BONES', '', ''),
	('シャフト', 'SHAFT', '', 'Shaft, Inc.'),
	('株式会社ガイナックス', 'GAINAX', '', ''),
	('アニメイトフィルム', 'アニメイトフィルム', 'アニメイト 的前身', ''),
	('シンエイ動画株式会社', 'SHIN-EI動畫', '新銳動畫、新映動畫（シンエイどうが、英: SHIN-EI ANIMATION Co., Ltd.）。テレビ朝日の子会社。日本動画協会正会員。 ', ''),
	('株式会社東京ムービー', '東京ムービー', '', ''),
	('オー・エル・エム', 'OLM', 'OLM, Inc.，全稱Oriental Light Magic；OLM TEAM IGUCHI', ''),
	('株式会社アニメインターナショナルカンパニー', 'AIC', '動畫國際公司（英語：Anime International Company, Inc.，縮寫：AIC）', ''),
	('株式会社サテライト', 'SATELIGHT', 'SATELIGHT8bit', 'SATELIGHT Inc.'),
	('株式会社アクタス', 'Actas', '', 'Actas Inc.'),
	('ビィートレイン株式会社', 'BEE TRAIN', 'BEE TRAIN Production Inc.', ''),
	('株式会社プロダクション リード', 'PRODUCTION REED', 'Production REED、PRODUCTION REED CO.,LTD.', ''),
	('Digimation', 'Digimation', '之後與 GONZO 合併', ''),
	('有限会社ゼクシズ', 'ZEXCS', '英語：ZEXCS Inc.', ''),
	('株式会社童夢', '童夢', '，英語：DAUME CO., LTD.', ''),
	('株式会社スタジオコメット', 'Studio COMET', '英語：STUDIO COMET Co.,Ltd.', ''),
	('有限会社カオスプロジェクト', 'Chaos Project', '', ''),
	('株式会社エー・シー・ジー・ティー', 'A・C・G・T', '（英: ACGT Co.,Ltd.）', ''),
	('ユーフォーテーブル有限会社', 'ufotable', 'ufotable, Inc.', ''),
	('株式会社ガンジス', 'GANSIS', '（GANSIS, Inc.）', ''),
	('キッズステーション', 'KIDS STATION', '東京KIDS', ''),
	('株式会社テレビ東京', '東京電視台', 'TV TOKYO Corporation', ''),
	('東宝株式会社', '東寶', '', ''),
	('株式会社動画工房', '動畫工房', '', ''),
	('株式会社京都アニメーション', '京都動畫', '（きょうとアニメーション、英: Kyoto Animation Co., Ltd.）は、日本のアニメ制作会社。略称は京アニ（きょうアニ）、京都アニメ（きょうとアニメ）。', ''),
	('芸者東京エンターテインメント株式会社', '藝者東京娛樂', '', ''),
	('株式会社手塚プロダクション', '手塚Productions', '', ''),
	('ジェイ・シー・エフ株式会社（学協）', 'ジェイ・シー・エフ', '', ''),
	('株式会社サンリオ', '三麗鷗', '株式会社サンリオ（英: Sanrio Company, Ltd.）', ''),
	('株式会社A-1 Pictures', 'A-1 Pictures', '（エー・ワン・ピクチャーズ、略称: A1P）', ''),
	('株式会社アスリード', 'asread', '', ''),
	('有限会社アームス', 'Arms', '（英: Arms Corporation）', ''),
	('株式会社メディアビー', 'BEE･MEDIA', '', ''),
	('有限会社ブレインズ・ベース', E'Brain\'s･Base', E'有限会社ブレインズ・ベース（英: Brain\'s Base Inc.）', ''),
	('コード株式会社', 'Code', '', ''),
	('株式会社デイヴィッドプロダクション', 'David Production', '（日語：株式会社デイヴィッドプロダクション，英語：david production Inc.）', ''),
	('ダックスプロダクション', 'DAX Production', '', ''),
	('株式会社ディオメディア', 'diomedéa', 'Diomedea、diomedéa inc.', ''),
	('有限会社フィール', 'feel.', '', ''),
	('ジーケーエンターテインメント', 'GK Entertainment', 'GK entertainment co., Ltd', ''),
	('株式会社GoHands', 'GoHands', '（ゴーハンズ），英語：GoHands Co.,Ltd', ''),
	('ヒウォンエンタテインメント', 'Heewon Entertainment', '', ''),
	('フッズエンタテインメント株式会社', 'Hoods Entertainment', '株式會社Hoods（フッズエンタテインメント株式会社；Hoods Entertainment inc）', ''),
	('JM Animation', 'JM ANIMATION', 'JM Animation Co.', ''),
	('株式会社キネマシトラス', 'KINEMA CITRUS', 'KINEMA CITRUS Co., Ltd.', ''),
	('株式会社セブン・アークス', 'Seven Arcs', 'SEVEN・ARCS Co., Ltd.', ''),
	('有限会社SynergySP', 'Synergy SP', '有限会社SynergySP（シナジーエスピー） シナジーSP、シナジーエスピー', ''),
	('株式会社SILVER LINK.', 'SILVER LINK.', '株式会社SILVER LINK.（シルバーリンク、英: SILVER LINK., Inc.）', ''),
	('有限会社M.S.C', 'M.S.C', '', ''),
	('株式会社マングローブ', 'Manglobe', '株式会社マングローブ（英: manglobe INC.）', ''),
	('株式会社日本アドシステムズ', 'NAS', '株式会社日本アドシステムズ（にほんアドシステムズ、英: Nihon Ad Systems inc.）', ''),
	('日本放送協会', 'NHK Enterprises', '（にっぽんほうそうきょうかい、英: Japan Broadcasting Corporation[2]、略称: NHK）', ''),
	('有限会社ノーマッド', 'NOMAD', 'アニメーションスタジオ ノーマッド｜NOMAD,Inc. VENUS PROJECT -CLIMAX-（英: NOMAD, Inc.）', ''),
	('株式会社ピーエーワークス', 'P.A. Works', '株式会社ピーエーワークス（英: P.A.WORKS Co.,Ltd.）', ''),
	('株式会社WHITE FOX', 'WHITE FOX', '（ホワイトフォックス）', ''),
	('株式会社ゆめ太カンパニー', 'YUMETA', '（ゆめたカンパニー、英: YUMETA CO., LTD.）', '');
	('トライネットエンタテインメント', 'TRINET ENTERTAINMENT', '', ''),
	('ピクチャーマジック', 'Picture Magic', '', ''),
	('株式会社スタジオヴォルン', 'Studio Kelmadick', '（日语：株式会社スタジオヴォルン，英語：studio VOLN）', ''),

	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
	-- ('', '', '', ''),
